name: Main workflow

on:
  workflow_dispatch:

jobs:
  linter_test:
    name: Test backend with linter
    runs-on: ubuntu-latest
    steps:
      # Копирование репозитория из GitHub
      - uses: actions/checkout@v4
      - name: Set up Python
      # Установка python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.2
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.lint.txt
      - name: Test with flake8
        run: |
          cd backend/
          python -m flake8 .

  build_and_push_to_docker_hub:
  name: Push Docker image to DockerHub
  runs-on: ubuntu-latest
  needs:
    - linter_test
    # - pytest_test
  steps:
    - name: Check out the repo
      # Получение исходного кода из репозитория
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      # Установка сборщика контейнеров Docker
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker
      # Авторизация на Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to DockerHub
      # Одновременный билд и пуш образа в Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: ./ecom/
        push: true
        tags: dartanyun/ecom_backend:latest
      # Одновременный билд и пуш образа в Docker Hub
    - name: Push to Docker Hub gateway
      uses: docker/build-push-action@v3
      with:
        context: ./src/infra/
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/tte_gateway:latest
