version: '3.3'

volumes:
  ecom_pg_data:
  static:

services:
  db:
    image: postgres:16.1-alpine3.19
    env_file: .env
    container_name: db
    volumes:
      - ecom_pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: backend
    entrypoint: /app/backend_entrypoint.sh
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    env_file: .env
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static/
    depends_on:
      - backend
